CLASS_EN_AR = {
    "Dog": "كلب",
    "Hello": "مرحبا",
    "No": "لا",
    "Thanks": "شكرا",
    "fine": "بخير",
    "love": "حب",
    "me": "أنا",
    "mother": "أم",
    "smile": "ابتسامة",
    "sorry": "آسف",
    "sunday": "الأحد",
    "yes": "نعم",
    "you": "أنت",
}
